### ISSUE TITLE
update freedesktop runtime to 20.08

### ISSUE THREAD

**Issue by eszlari** [flathub/org.jamovi.jamovi#62] opened 2020-10-10 21:25 UTC

**Comment by sjentsch** [comment] 2021-08-25 09:25
Working on it with Jonathon.

**Comment by hfiguiere** [comment] 2021-09-14 17:17
21.08 is available now.

**Comment by sjentsch** [comment] 2021-09-14 18:10
It currently doesn't even compile with 20.08.
https://github.com/flatpak/flatpak-builder/issues/415

**Comment by hfiguiere** [comment] 2021-09-14 18:15
it's just twice the work.

**Comment by jonathon-love** [comment] 2021-09-14 21:58
> Unlikely that moving to 21.08 will make that any better.

haha, i have the opposite thought ... works with 19.08 and earlier, it works with 20.08 but after being built on flathub crashes, there's a very good chance that on 21.08 it will **just work** :)

**Comment by sjentsch** [comment] 2021-09-15 14:50
Wishful thinking...
Nope, it doesn't compile:
Error: module gsl: Child process exited with code 137
I tried upgrading gsl to 2-7 but that did not solve it either.

**Comment by hfiguiere** [comment] 2021-09-15 22:35
it's thin as an error message to be able to help.

**Comment by hfiguiere** [comment] 2021-10-12 20:12
dupe of #74 that is still open to followup on runtime issues.

**Closed by hfiguiere** 2021-10-12 20:12 UTC
